### ISSUE TITLE
Searching does not bring exact matches

### ISSUE THREAD

**Issue by RyanSept** [CodeForAfricaLabs/HealthTools.API#4]
When a search is carried out on the api, the search results brought aren't that accurate. For example searching for a doctor "john" will bring up multiple doctors with different names who went to John Hopkins university before the first "john" shows up(https://api.healthtools.codeforafrica.org/doctors/search.json?q=john). It is due to the searching being done over the qualifications fields

**Comment by DavidLemayian** [comment]
This is happening because we aren't parsing fields to search and their importance to cloudsearch [here](https://github.com/CodeForAfricaLabs/HealthTools.KE-api/blob/master/healthtools_ke_api/views/doctors.py#L73).

Here are a couple of links that should help:

- [Cloud Search Documentation](http://docs.aws.amazon.com/cloudsearch/latest/developerguide/searching-text.html#searching-text-terms)
- [Boto3 Documentation](http://boto3.readthedocs.io/en/latest/reference/services/cloudsearchdomain.html#CloudSearchDomain.Client.search)

**Comment by DavidLemayian** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[HTools KE] Add doctors and clinical officers to API](https://trello.com/c/XUYXo3Px/19-htools-ke-add-doctors-and-clinical-officers-to-api)
